### PR TITLE
Correcting versions of yoyo deps in example templates

### PR DESCRIPTION
**Pull request by lsnape**
Tried to test drive your templates but couldn't find the deps in Clojars. Changed the snapshot versions to fixed `0.0.1`. Hope that's right!

### CODE REVIEW

**Comment by jarohen** [comment]
Gah, snapshots... 

Cheers mate, will merge it when I'm next at a computer :) 

J

**Comment by jarohen** [comment]
Thanks Luke - merged and deployed :)

**Comment by jarohen** [comment]
what do you think, btw - along the right lines?

**Comment by lsnape** [comment]
I only found out about it late last night so I haven't had a chance to look at it properly. The idea is interesting though and I think it has potential. I plan to take a closer look over the next few days. Feedback to come!

**Pull request merged**
