### PR TITLE
Update main.clj

### PR DESCRIPTION
**Pull request by weaver-viii**

### CODE REVIEW

**Comment by jarohen** [comment]
Thanks :) Will merge when I get back

**Comment by weaver-viii** [comment]
I'm very like your approach to write code. I'm your fan)

**Comment by jarohen** [comment]
Cheers :) Would be great to hear if you have any suggestions for the library/code patterns/etc!

All merged and released to Clojars - thanks for the PR :)

**Comment by weaver-viii** [comment]
Yo!) Thanks for your awesome libraries!) :v: Ok, I will do when I have some! :D

**Pull request merged**
